# Launch Elasticsearch
version: '3.2'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.8.2
    volumes:
      - source: $HOME/pipelines
        target: /usr/share/logstash/pipeline
        type: bind
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch
#    environment:
#      - "ELASTICSEARCH_URL": b6umvbypc-elasticsearch.services.clever-cloud.com

networks:
  elk:
    driver: bridge